// @generated by `PRINT_STATE_FIXTURES=1 cargo test -p online-core --test state_fixtures`: do not edit by hand.
// The `holt` case of tests/cases/mod.rs after 40 rows, and its next 16 rows.
pub const FIXTURE: crate::cases::Fixture = crate::cases::Fixture {
    name: "holt",
    variant: "Holt",
    schema: 38,
    writer: "macos-aarch64",
    state: "\
        82ae736368656d615f76657273696f6e26a56d6f64656c81a4486f6c7488a363666785a96e5f7461726765747302af6c\
        6576656c5f68616c665f6c696665cb4024000000000000af7472656e645f68616c665f6c696665cb4044000000000000\
        aa6d696e5f776569676874cb4008000000000000a57472656e64c3a56c6576656c92cb3fd01a731c12e20acbbfdfe58c\
        e3ed1df4a57472656e6492cb3f585070b59313eecb3f585070b59313f7a47365656e92c3c3a5775f73756dcb4024d8df\
        aed00369a573696e636592cb0000000000000000cb0000000000000000a7775f6c6576656c92cb402312514f0a1a67cb\
        402312514f0a1a67a7775f7472656e6492cb4036f6c9620c767ccb4036f6c9620c767c",
    x: &[
    ],
    y: &[
        None, None,
        Some(0x3fcbf3b3813dfdae), Some(0xbfe103131fb08094),
        Some(0x3fd399057c9e064d), Some(0xbfdc66fa8361f9b4),
        Some(0x3fd15a696db8bf2a), Some(0xbfdea596924740d6),
        Some(0x3fd6338e3c19dffe), Some(0xbfd9cc71c3e62002),
        Some(0x3fd453c31c6151dc), Some(0xbfdbac3ce39eae24),
        Some(0x3fd47777041b9bd9), Some(0xbfdb8888fbe46428),
        Some(0x3fd429296362fdef), Some(0xbfdbd6d69c9d0210),
        Some(0x3fd16ba5adc021b5), Some(0xbfde945a523fde4a),
        Some(0x3fca2736a9feb734), Some(0xbfe1763255805233),
        Some(0x3fcdb2b1236d75ad), Some(0xbfe09353b724a295),
        None, None,
        Some(0x3fd3eca97e3da5fe), Some(0xbfdc135681c25a02),
        Some(0x3fd3207e8f67592d), Some(0xbfdcdf817098a6d2),
        Some(0x3fd20c3616821ff2), Some(0xbfddf3c9e97de00e),
        Some(0x3fcfec0466ec7452), Some(0xbfe004fee644e2ec),
    ],
    d: &[
        0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000,
        0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000,
        0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000,
        0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000,
    ],
    w: &[
        0x0000000000000000, 0x3ff0000000000000, 0x3fe0000000000000, 0x3ff0000000000000,
        0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 0x4004000000000000,
        0x3ff0000000000000, 0x0000000000000000, 0x3ff0000000000000, 0x3fe0000000000000,
        0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000,
    ],
    pred: &[
        0x3fd032c38cc8751e, 0xbfdfcd3c73378ae0, 0x3fd04b13fd7e0832, 0xbfdfb4ec0281f7cc,
        0x3fd0223cfc19cf6c, 0xbfdfddc303e63094, 0x3fd06a859a660e1c, 0xbfdf957a6599f1e4,
        0x3fd09ca1913da97b, 0xbfdf635e6ec25685, 0x3fd14bbf2c09f51f, 0xbfdeb440d3f60ae1,
        0x3fd1b953f87b936e, 0xbfde46ac07846c92, 0x3fd22046081aa517, 0xbfdddfb9f7e55ae9,
        0x3fd2b7a3d0bb4845, 0xbfdd485c2f44b7bc, 0x3fd2ca42617862e7, 0xbfdd35bd9e879d1a,
        0x3fd2f75cb01a5e4f, 0xbfdd08a34fe5a1b2, 0x3fd2ca6c6b2167d2, 0xbfdd359394de982f,
        0x3fd2f5f5c9b3d370, 0xbfdd0a0a364c2c91, 0x3fd33793745495bf, 0xbfdcc86c8bab6a42,
        0x3fd361705d7dca1e, 0xbfdc9e8fa28235e3, 0x3fd36f7771f29284, 0xbfdc90888e0d6d7d,
    ],
    n_eff: &[
        0x4024d8dfaed00369, 0x4023737ab2ce0d23, 0x40242604b9bb3201, 0x4023cc99f4e8313f,
        0x4024792c1d37e75c, 0x40251a2fcae4ed24, 0x4025b06b1cc7c628, 0x40263c96ed3bae6a,
        0x4029bf5fb59280a8, 0x402a05f822677b84, 0x402847d64da31b1f, 0x4028a794c34bd54a,
        0x402800e9d4903be4, 0x402865682cb32c7e, 0x4028c32bb3dc1261, 0x40291aa7c93ccd57,
    ],
    extra: &[
    ],
    n_features: 0,
    n_targets: 2,
    n_pred: 2,
    n_extra: 0,
};
