// @generated by `PRINT_STATE_FIXTURES=1 cargo test -p online-core --test state_fixtures`: do not edit by hand.
// The frozen state fixtures, one file a case of tests/cases/mod.rs.

/// The schema every fixture here was written at.
pub const SCHEMA: u32 = 45;

pub mod ew_cov_accumulator {
    include!("ew_cov_accumulator.rs");
}
pub mod ewridge {
    include!("ewridge.rs");
}
pub mod ewridge_window {
    include!("ewridge_window.rs");
}
pub mod ewridge_leverage {
    include!("ewridge_leverage.rs");
}
pub mod rls {
    include!("rls.rs");
}
pub mod lasso {
    include!("lasso.rs");
}
pub mod lasso_window {
    include!("lasso_window.rs");
}
pub mod kalman {
    include!("kalman.rs");
}
pub mod huber {
    include!("huber.rs");
}
pub mod quantile {
    include!("quantile.rs");
}
pub mod ftrl {
    include!("ftrl.rs");
}
pub mod ew_cov {
    include!("ew_cov.rs");
}
pub mod ew_cov_window {
    include!("ew_cov_window.rs");
}
pub mod sgd {
    include!("sgd.rs");
}
pub mod sgd_huber {
    include!("sgd_huber.rs");
}
pub mod sgd_eps {
    include!("sgd_eps.rs");
}
pub mod sgd_logistic {
    include!("sgd_logistic.rs");
}
pub mod pa {
    include!("pa.rs");
}
pub mod holt {
    include!("holt.rs");
}
pub mod kmeans_warming {
    include!("kmeans_warming.rs");
}
pub mod kmeans {
    include!("kmeans.rs");
}
pub mod micro {
    include!("micro.rs");
}
pub mod ew_class {
    include!("ew_class.rs");
}
pub mod ew_class_window {
    include!("ew_class_window.rs");
}
pub mod seqtest {
    include!("seqtest.rs");
}
pub mod marginal_lags {
    include!("marginal_lags.rs");
}
pub mod marginal_bins {
    include!("marginal_bins.rs");
}
pub mod marginal_window {
    include!("marginal_window.rs");
}
pub mod deco {
    include!("deco.rs");
}
pub mod rcov {
    include!("rcov.rs");
}
pub mod hmm {
    include!("hmm.rs");
}
pub mod corrchange_monitor {
    include!("corrchange_monitor.rs");
}
pub mod corrchange_sequential {
    include!("corrchange_sequential.rs");
}
pub mod bocpd_warming {
    include!("bocpd_warming.rs");
}
pub mod bocpd {
    include!("bocpd.rs");
}

/// Every fixture, in the cases' order.
pub const ALL: &[&crate::cases::Fixture] = &[
    &ew_cov_accumulator::FIXTURE,
    &ewridge::FIXTURE,
    &ewridge_window::FIXTURE,
    &ewridge_leverage::FIXTURE,
    &rls::FIXTURE,
    &lasso::FIXTURE,
    &lasso_window::FIXTURE,
    &kalman::FIXTURE,
    &huber::FIXTURE,
    &quantile::FIXTURE,
    &ftrl::FIXTURE,
    &ew_cov::FIXTURE,
    &ew_cov_window::FIXTURE,
    &sgd::FIXTURE,
    &sgd_huber::FIXTURE,
    &sgd_eps::FIXTURE,
    &sgd_logistic::FIXTURE,
    &pa::FIXTURE,
    &holt::FIXTURE,
    &kmeans_warming::FIXTURE,
    &kmeans::FIXTURE,
    &micro::FIXTURE,
    &ew_class::FIXTURE,
    &ew_class_window::FIXTURE,
    &seqtest::FIXTURE,
    &marginal_lags::FIXTURE,
    &marginal_bins::FIXTURE,
    &marginal_window::FIXTURE,
    &deco::FIXTURE,
    &rcov::FIXTURE,
    &hmm::FIXTURE,
    &corrchange_monitor::FIXTURE,
    &corrchange_sequential::FIXTURE,
    &bocpd_warming::FIXTURE,
    &bocpd::FIXTURE,
];
