// @generated by `PRINT_STATE_FIXTURES=1 cargo test -p online-polars --test state_fixtures`: do not edit by hand.
// The frozen fixtures of a bank file and its helpers' states.

pub mod bank {
    include!("bank.rs");
}
pub mod with_windows {
    include!("with_windows.rs");
}
pub mod refresh_time {
    include!("refresh_time.rs");
}

/// Every fixture.
pub const ALL: &[&crate::Fixture] = &[
    &bank::FIXTURE,
    &with_windows::FIXTURE,
    &refresh_time::FIXTURE,
];
