"""Run the docs/PLAN.md [validate] experiments and print a markdown report.

Usage: uv run python scripts/validate.py [--rows N]

Uses the public intraday dataset (cached under .cache/) when available and the
seeded synthetic generator otherwise, and writes nothing: pipe stdout into
docs/VALIDATION.md.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import polars as pl

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tests"))

import polars_online as po  # noqa: E402
from data import VALIDATION_DATES as DATES  # noqa: E402
from data import public_intraday, synthetic  # noqa: E402


def load(rows: int) -> tuple[pl.DataFrame, str, list[str], list[str]]:
    """Returns (df, source, features, targets)."""
    try:
        raw = public_intraday(DATES)
        source = (
            f"public intraday (BTCUSDT 1m, Binance public dump, "
            f"{DATES[0]}..{DATES[-1]}, {len(DATES)} days)"
        )
    except RuntimeError:
        df, _ = synthetic(
            seed=1234, n_groups=1, n_rows=rows or 5000, k=4, n_targets=2, null_frac=0.0
        )
        return df, "synthetic (offline fallback)", ["x0", "x1", "x2", "x3"], ["y0", "y1"]

    # Simple, honest intraday features: past returns and volume/activity
    # signals. Targets are strictly future returns, so nothing leaks.
    df = (
        (raw.head(rows) if rows > 0 else raw)
        .with_columns(
            lr=(pl.col("close") / pl.col("close").shift(1)).log(),
            rng=(pl.col("high") - pl.col("low")) / pl.col("close"),
            vol_z=(pl.col("volume") - pl.col("volume").rolling_mean(60))
            / pl.col("volume").rolling_std(60),
            trades_z=(pl.col("n_trades") - pl.col("n_trades").rolling_mean(60))
            / pl.col("n_trades").rolling_std(60),
        )
        .with_columns(
            x0=pl.col("lr"),
            x1=pl.col("lr").rolling_sum(5),
            x2=pl.col("vol_z"),
            x3=pl.col("trades_z"),
            # Targets are strictly future returns, so nothing leaks.
            y0=pl.col("lr").shift(-1),
            y1=pl.col("lr").rolling_sum(5).shift(-5),
        )
        .drop_nulls(["x0", "x1", "x2", "x3", "y0", "y1"])
        .with_columns(group=pl.lit("BTCUSDT"))
    )
    return df, source, ["x0", "x1", "x2", "x3"], ["y0", "y1"]


def run(df: pl.DataFrame, specs: list[dict], targets: list[str]) -> pl.DataFrame:
    bank = po.ModelBank(specs)
    out = bank.fit_predict(df)
    return po.eval.compare_specs(out, [s["name"] for s in specs], targets=targets)


def section(title: str, body: str) -> None:
    print(f"\n## {title}\n")
    print(body)


def table(df: pl.DataFrame, cols: list[str]) -> str:
    df = df.select(cols)
    head = "| " + " | ".join(cols) + " |"
    sep = "|" + "|".join("---" for _ in cols) + "|"
    rows = []
    for r in df.iter_rows():
        cells = [f"{v:.6g}" if isinstance(v, float) else str(v) for v in r]
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join([head, sep, *rows])


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rows", type=int, default=0, help="cap the row count (0 = use everything)")
    args = ap.parse_args()

    df, source, feats, targets = load(args.rows)
    target = targets[0]
    common = dict(
        targets=[target],
        features=feats,
        halflife=500.0,
        min_periods=50.0,
        standardize=True,
    )

    print("# Validation results")
    print()
    print("Generated by `scripts/validate.py`. Re-run with:")
    print()
    print("```sh")
    print("uv run python scripts/validate.py > docs/VALIDATION.md")
    print("```")
    print()
    print(f"- Data: {source}")
    print(f"- Rows: {df.height}, features: {feats}, targets: {targets}")
    print(f"- Polars {pl.__version__}, polars-online {po.__version__}")

    # ---- 1. solve schedule: is halflife/50 the right default? ----
    hl = 500.0
    divisors = [1, 5, 10, 50, 200, 1000]
    specs = []
    for d in divisors:
        specs.append(po.spec.ewridge(f"s{d}", ridge=1e-4, solve_every=hl / d, **common))
    t0 = time.perf_counter()
    res = run(df, specs, [target])
    elapsed = time.perf_counter() - t0
    res = res.with_columns(divisor=pl.col("spec").str.strip_prefix("s").cast(pl.Int64)).sort(
        "divisor"
    )
    best = res.sort("mse").row(0, named=True)
    section(
        "1. Solve schedule (`solve_every` default = halflife/50) [validate]",
        f"Solving every `halflife/d` clock units, halflife = {hl}. "
        f"All schedules share one accumulator, so this is a free experiment "
        f"({elapsed:.2f}s for {len(divisors)} schedules).\n\n"
        + table(res, ["divisor", "n", "r2", "ic", "hit_rate", "mse"])
        + f"\n\n**Result:** lowest MSE at divisor {best['divisor']} "
        f"(mse {best['mse']:.6g}).",
    )

    # ---- 2. standardize default ----
    specs = [
        po.spec.ewridge("plain", ridge=1e-4, **{**common, "standardize": False}),
        po.spec.ewridge("std", ridge=1e-4, **{**common, "standardize": True}),
    ]
    res = run(df, specs, [target])
    section(
        "2. `standardize` default (false for ridge, true for lasso)",
        table(res, ["spec", "n", "r2", "ic", "mse"]),
    )

    # ---- 3. elastic net l1_ratio [validate] ----
    # l1_ratio only bites where the penalty is nonzero, so the comparison is
    # made at the penalized path points, not at lambda = 0.
    path = [1e-2, 1e-3, 1e-4, 0.0]
    specs = [
        po.spec.lasso(
            f"l1_{int(r * 100)}",
            lasso_path=path,
            l1_ratio=r,
            targets=[target],
            features=feats,
            halflife=hl,
            min_periods=50.0,
        )
        for r in (1.0, 0.5, 0.1)
    ]
    res = run(df, specs, [target]).filter(~pl.col("slot").str.ends_with("l0"))
    section(
        "3. Elastic net `l1_ratio` [validate]",
        "Lasso path "
        + str(path)
        + ". `l1_ratio` = 1 is pure lasso; below 1 the penalty is part ridge. "
        "The lambda = 0 slot is excluded because `l1_ratio` cannot affect it.\n\n"
        + table(res, ["spec", "slot", "n", "r2", "ic", "mse"]),
    )

    # ---- 4. share_p [validate] ----
    kal = dict(
        targets=[target],
        features=feats,
        coef_halflife=200.0,
        halflife=hl,
        min_periods=50.0,
    )
    kal_multi = {**kal, "targets": targets}
    specs = [
        po.spec.kalman("per_target_p", share_p=False, **kal_multi),
        po.spec.kalman("shared_p", share_p=True, **kal_multi),
    ]
    t0 = time.perf_counter()
    res = run(df, specs, targets)
    share_elapsed = time.perf_counter() - t0
    section(
        "4. Kalman `share_p` approximation [validate]",
        f"Two targets ({targets}) with very different noise levels, so the "
        f"shared-P approximation is doing real work. Both specs run in "
        f"{share_elapsed:.2f}s total.\n\n"
        + table(res, ["spec", "slot", "target", "n", "r2", "ic", "mse"]),
    )

    # ---- 5. model comparison at matched settings ----
    specs = [
        po.spec.ewridge("ewridge", ridge=1e-4, **common),
        po.spec.rls(
            "rls", ridge=1e-4, targets=[target], features=feats, halflife=hl, min_periods=50.0
        ),
        po.spec.kalman("kalman", **kal),
        po.spec.lasso(
            "lasso",
            lasso_path=[1e-3, 1e-4, 0.0],
            targets=[target],
            features=feats,
            halflife=hl,
            min_periods=50.0,
        ),
    ]
    res = run(df, specs, [target])
    section(
        "5. Models at matched settings",
        table(res, ["spec", "slot", "n", "r2", "ic", "hit_rate", "mse"]),
    )

    print()
    print("---")
    print()
    print(
        "Predictions are out-of-sample by construction (docs/PLAN.md hard rule 2): "
        "each row is predicted before the model sees its target. Negative R^2 on "
        "financial data is normal and expected - it means the model does worse than "
        "the realized in-window mean, not that anything is broken."
    )


if __name__ == "__main__":
    main()
