"""Type stub for the pyo3 module (crates/online-py/src/lib.rs). The wrappers in
this package are what users call; this is what lets a type checker follow them
into the native calls. ``tests/test_kwargs_typing.py`` checks it names every
attribute the built module has, so it cannot go stale silently."""

import polars as pl

class ModelBank:
    def __init__(self, specs_json: str) -> None: ...
    def fit_predict(self, df: pl.DataFrame) -> list[pl.Series]: ...
    def save(self, path: str) -> None: ...
    def save_bytes(self) -> bytes: ...
    @staticmethod
    def load(path: str, specs_json: str | None = None) -> ModelBank: ...
    @staticmethod
    def load_bytes(bytes: bytes, specs_json: str | None = None) -> ModelBank: ...
    def output_fields(self) -> list[list[str]]: ...
    def solve_failures(self) -> list[list[tuple[str | None, int]]]: ...
    def gram(
        self, spec: int, group: str | None = None
    ) -> list[
        tuple[
            str | None,  # group
            str,  # instance
            int,  # k
            float,  # n_eff
            list[float],  # means
            list[float],  # comoments, k*k row-major
            list[list[float]],  # cross_moments, one row per target
            list[float],  # target_weights
        ]
    ]: ...
    def spec_names(self) -> list[str]: ...
    def specs_json(self) -> str: ...
    def groups(self) -> list[list[tuple[str | None, int, float | None]]]: ...
    def drop_groups(self, keys: list[str | None], spec: int | None = None) -> int: ...
    def rows_seen(self) -> int: ...

def validate_spec(spec_json: str) -> None: ...
def run_config(config_json: str) -> tuple[int, int]: ...
def spec_output_index(spec_json: str) -> str: ...
def spec_output_fields(spec_json: str) -> list[str]: ...
def native_version() -> str: ...
def schema_version() -> int: ...
def model_kinds() -> list[str]: ...
